### ISSUE TITLE
Unhadled exception at line 141 , column 9 in http://127.0.0.1:81/scripts/bower_components/requirejs/require.js

### ISSUE THREAD

**Issue by krishnazure** [LukeTillman/killrvideo-csharp#1]
0x800a139e - JavaScript runtime error:Script error for : knockout -postbox. 

When i run the code , its complies fine and when i click on Register. It fails with the following JavaScript error. I am running the code locally..

**Comment by LukeTillman** [comment]
Thanks for the heads-up. Looks like one of the JavaScript libraries wasn't checked-in correctly.  If you try pulling down the latest from master, it should be working now.
