### ISSUE TITLE
Lost access to Cluster

### ISSUE THREAD

**Issue by krishnazure** [LukeTillman/killrvideo-csharp#4]
I checked if i can access my Cassandra Cluster http://localhost:8888/opscenter/index.html ..  I encounter the following error.. 

![cassandra error](https://cloud.githubusercontent.com/assets/5904129/6770279/c78cc35e-d091-11e4-8762-4af94ef41d47.jpg)

**Comment by LukeTillman** [comment]
Have you tried connecting to it via `cqlsh` or DevCenter?  See my blog post on Windows Cassandra development for details and how to check if the services are running and some of the tools available to you:

http://www.luketillman.com/developing-with-cassandra-on-windows/

If you're having issues with OpsCenter, I suggest posting a question to StackOverflow where someone from the OpsCenter team at DataStax might be able to assist.
